/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* src = "and_gate.sv:2.1-10.10" *)
module and_gate(a, b, y);
  (* src = "and_gate.sv:3.21-3.22" *)
  input a;
  wire a;
  (* src = "and_gate.sv:4.21-4.22" *)
  input b;
  wire b;
  (* src = "and_gate.sv:5.21-5.22" *)
  output y;
  wire y;
  assign y = a & b;
endmodule
