name: Verilator CI

on:
  push:
    paths:
      - 'rtl/**'
      - 'tb/**'
      - 'scripts/**'
      - '.github/workflows/verilator.yml'

  pull_request:
    paths:
      - 'rtl/**'
      - 'tb/**'
      - 'scripts/**'
      - '.github/workflows/verilator.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Verilator CI
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            verilator/verilator:v5.050 \
            -c "verilator --version && python3 scripts/run.py dff"